### ISSUE TITLE
XLSX export is garbled

### ISSUE THREAD

**Issue by almereyda** [ohmyform/ohmyform#163] opened 2022-03-02 01:39 UTC
#### What's this issue about?

When exporting a form, the columns are misaligned in the XLSX export.

#### Expected behavior

When exporting the submissions into a spreadsheet table, all contents are placed according to their contents.

#### Actual behavior

<details>

<summary>Table pasted from garbled XLSX output:</summary>

Submission ID | Created | Last Change | Country | City | User Agent | Device | Name (textfield) | E-Mail (textfield) | Membership type (radio) | Confirmation (yes_no) | Subscription (yes_no) | Please tell us your opinion! (textarea) | Status (hidden)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
XPlRwL | 2022-03-02T00:14:03.314Z | 2022-03-02T00:14:28.380Z |   |   | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0 | desktop | "120" | YES | YES | "Example Person" | "Best in class!" | "haha@example.com" |  
lndWP7 | 2022-03-02T00:14:33.144Z | 2022-03-02T00:18:14.815Z |   |   | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0 | desktop | "haha@example.com" | "120" | YES | YES | "Example Person" | "Best in class!" |  
DPBjPV | 2022-03-02T00:26:35.200Z | 2022-03-02T00:26:55.022Z |   |   | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0 | desktop | YES | YES | "Example Person" | "haha@example.com" | "120" | "Best in class!" |  
DwroZX | 2022-03-02T00:28:24.647Z | 2022-03-02T00:28:49.828Z |   |   | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0 | desktop | "haha@example.com" | "120" | "Best in class!" | YES | YES | "Example Person" |  
YwX1Zj | 2022-03-02T00:50:00.289Z | 2022-03-02T00:50:18.793Z |   |   | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0 | desktop | YES | "120" | YES | "yala" | "Best in class!" | "yala+haha@example.com" |  
RnNmPO | 2022-03-02T00:50:33.489Z | 2022-03-02T00:52:04.628Z |   |   | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0 | desktop | "hihi+haha@example.com" | "Best in class!" | "yala" | YES | YES | "120" |  
anWAZx | 2022-03-02T00:52:57.063Z | 2022-03-02T00:53:20.471Z |   |   | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0 | desktop | "Best in class!" | "yala" | "120" | YES | "haha@example.com" | YES |  
QnJlZX | 2022-03-02T01:05:16.558Z | 2022-03-02T01:05:35.639Z |   |   | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0 | desktop | "person" | "person@example.com" | YES | YES | "Best!" | "120" |  
Jnp3PN | 2022-03-02T00:52:55.163Z | 2022-03-02T00:52:55.163Z |   |   | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0 | desktop |   |   |   |   |   |   |  
EnE2wa | 2022-03-02T00:52:14.245Z | 2022-03-02T00:52:14.245Z |   |   | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0 | desktop |   |   |   |   |   |   |  
6w73wY | 2022-03-02T00:26:57.231Z | 2022-03-02T00:26:57.231Z |   |   | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0 | desktop |   |   |   |   |   |   |  
jP5Nn3 | 2022-03-02T00:13:14.227Z | 2022-03-02T00:13:14.227Z |   |   | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0 | desktop |   |   |   |   |   |   |  
yw9Dn3 | 2022-03-02T00:48:46.170Z | 2022-03-02T00:48:46.170Z |   |   | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0 | desktop |   |   |   |   |   |   |  

</details>

After unfolding the table, scroll to the right and back up to see the example columns which are misaligned. Here, from a membership sign up form. (Shift-Mousewheel will scroll to the right, even when you're in the upper part of the table.)

#### Steps to reproduce

1. Export submissions as XLSX
2. Open XLSX in LibreOffice Calc

#### Environment

Separate Docker containers rolling on the `latest` release, accessed through latest available Firefox on Fedora 35.

**Comment by ccoenen** [comment] 2022-03-11 08:56
I have the very same problem! In my case it only turned up because I _knew_ what was usually the least favorite choice and my statistical interpretation was **way** off from my usual results.

If I didn't have that context, I would have probably not noticed.

In my case, I did a 1-5 Stars rating of a few different methods I used with a group of students. So my results table looks like this:

![grafik](https://user-images.githubusercontent.com/124909/157833589-b306529e-167a-497a-b289-ec95bfd92873.png)

not easy to spot an error in "all numbers" fields. Here ware the two last rows from that table above as single entries:
![grafik](https://user-images.githubusercontent.com/124909/157834393-b3a09a07-3598-47a6-b779-75b4f5e7409d.png)

one can clearly see that the submissions have a different order from each other:
- Moodle, Video, Issue, PDF
- Video, Issue, Moodle, PDF

And the XLS-export just assigns these to its own order: Issue, Moodle, PDF, Video (which is the order in which the form is organized, but ALMOST NONE of my submissions are in that same order!).

**Comment by ccoenen** [comment] 2022-03-11 09:00
the result from graphql is still very rich in information. it has the same order as the visual output in the ohmyform ui. So the problem is in the xls conversion in the client.

**Comment by ccoenen** [comment] 2022-03-11 09:02
I would assume that it's here, but I'm still investigating:
https://github.com/ohmyform/ui/blob/674678dba30edd14073d5447bc11fa52bc280c41/components/form/admin/export.submission.action.tsx#L48

**Comment by ccoenen** [comment] 2022-03-11 09:13
the solution would be to iterate (again) over `form.data.form.fields` (.title}` again, and then use that to query all `data.fields` for the same title. Even better would probably be to use some internal identifier (not sure if `id` or `idx` are candidates, I do not know enough about the internal structure to do more than a guess here).

**Comment by ccoenen** [comment] 2022-03-13 13:55
I _believe_ this is the change that would be needed, but I sadly have no way of testing it. This is also why I can't offer a Pull Request. I do, however offer this snippet without any attribution to me and under any license appropriate and neccessary, if someone else would like to contribute it. In short: just take it :-D

Replaces these lines: https://github.com/ohmyform/ui/blob/23e67c8f7e65396782f48ef5dfeef56ec8e45da9/components/form/admin/export.submission.action.tsx#L68-L76
```diff
-        data.fields.forEach((field) => {
-          try {
-            fieldTypes[field.type]?.stringifyValue(field.value)
-
-            row.push(fieldTypes[field.type]?.stringifyValue(field.value))
-          } catch (e) {
-            row.push('')
-          }
-        })
+        form.data.form.fields.forEach(formField => {
+          const dataField = data.fields.find(f => f.field.title === formField.title)
+          try {
+            row.push(fieldTypes[dataField.type]?.stringifyValue(dataField.value))
+          } catch (e) {
+            row.push('')
+          }
+        })
```

**Comment by wodka** [comment] 2022-03-13 13:57
:/ I think now I get it - will try to fix that later today  and thx @ccoenen for preparing a fix!

**Comment by wodka** [comment] 2022-03-13 22:37
fixed in https://github.com/ohmyform/ui/commit/30ff2c96bca20c1641d9cbb96c34cce934e1afea

**Comment by ccoenen** [comment] 2022-03-13 23:34
Thank you for taking a look, but I fear there might be another problem. I commented over here (just tying it into this issue with this comment for reference):
https://github.com/ohmyform/ui/commit/30ff2c96bca20c1641d9cbb96c34cce934e1afea#r68602651

**Comment by ccoenen** [comment] 2022-03-26 15:29
I'm slightly irritated that there has been no further activity on this particular issue. I think this is 95% "there" already, I believe it's only missing the tiniest push.

**Comment by wodka** [comment] 2022-03-27 18:26
it is fixed now in https://github.com/ohmyform/ohmyform/releases/tag/1.0.3

**Comment by wodka** [comment] 2022-03-27 18:26
> I'm slightly irritated that there has been no further activity on this particular issue. I think this is 95% "there" already, I believe it's only missing the tiniest push.

still just a spare time project where I fix and test things once I find time :)

**Closed by wodka** 2022-03-27 18:26 UTC

**Comment by ccoenen** [comment] 2022-03-28 07:53
Can confirm that it is working now.
